version: '3'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /opt/data/mongo_dev:/data/db
    restart: always
  movies:
    image: "movies"
    hostname: movies
    ports:
      - "8080:8080"
    restart: always
    environment: 
      - MONGODB_ADDRS=mongodb:27017
      - STATUS_FILE_PATH=/home/configs/status.yml
