normal:
  success:
    status: 200
    code: 1001
    message: "Success"
  not_found:
    status: 404
    code: 1002
    message: "Not found"
  timeout:
    status: 500
    code: 1002
    message: "Timeout"
  bad_request:
    status: 400
    code: 1003
    message: "Bad request"
  internal:
    status: 500
    code: 1004
    message: "Internal server error"
  permission_deny:
    status: 400
    code: 1005
    message: "Permission deny"

user:
  created:
    status: 201
    code:   1105
    message: "Register successfully"
  duplicate_email:
    status: 400
    code: 1106
    message: "An email is existed"
  update_failed:
    status: 500
    code: 1107
    message: "User update failed"
  create_failed:
    status: 500
    code: 1107
    message: "Register user failed"
  delete_failed:
    status: 500
    code: 1108
    message: "Delete user failed"
  user_not_found:
    status: 400
    code: 1109
    message: "User not found"
  
auth:
  user_locked:
    status: 423
    code: 1201
    message: "Account is locked"
  email_not_exist:
    status: 401
    code: 1202
    message: "An email is not exist"
  password_wrong:
    status: 401
    code: 1203
    message: "Email/Password is invalid"
  unauthorized:
    status: 401
    code: 1204
    message: "Unauthorized"
  token_invalid:
    status: 401
    code: 1205
    message: "Token Invalid"
movie:
  created:
    status: 423
    code: 1301
    message: "Created"
  delete_failed:
    status: 500
    code: 1302
    message: "Delete movie failed"